name: calculadora_imc
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^0.22.0
  flutter_launcher_icons: ^0.9.0
  after_layout: ^1.1.0
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.1
  flutter_facebook_auth: ^0.2.1
  curved_navigation_bar: ^0.3.7
  font_awesome_flutter: ^9.1.0


flutter:
  uses-material-design: true

  assets:
    - assets/pages/login/
    - assets/pages/loading/
    - assets/pages/onboarding/

  fonts:
    - family: Oranienbaum
      fonts:
        - asset: assets/fonts/Oranienbaum-Regular.ttf
    
    - family: Benne
      fonts:
        - asset: assets/fonts/Benne-Regular.ttf

